--atom
--package ssh
--package emacs
--package lubuntu-artwork-14-04
--package lubuntu-artwork-14-10
--package lubuntu-artwork-15-04
--package lubuntu-artwork-15-10
--file fix-hdmipleaudio.sh
--file fix-volumekeys.sh
--file wrapper-fix-hdmipleaudio.sh
--file brcmfmac43455-sdio.txt
--file wrapper-fix-brcmfmac43455.sh
--file install-xForge.sh
--command wrapper-fix-hdmipleaudio.sh
--command wrapper-fix-brcmfmac43455.sh
