---

- name: manually load alsa sink
  lineinfile:
    path:   /etc/pulse/default.pa
    regexp: "^#load-module module-alsa-sink"
    state: present
    line:   "load-module module-alsa-sink device=hw:0,2"

- name: disable auto detect
  command: "sed -i '/### Automatically load driver modules depending on the hardware available/,/.endif/ s/^/# LINUXIUM #/' /etc/pulse/default.pa"
  warn: false
